version: "3.7"
services:
  client:
    image: gcr.io/omni-demo-304013/omni-web
    build:
      context: ./frontend
      dockerfile: Prod.Dockerfile
    ports:
      - "4000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: omnidb
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
  api:
    image: gcr.io/omni-demo-304013/omni-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --timeout 300 --bind 0.0.0.0:5000 app:app
    environment:
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "apiuser"
      MONGODB_PASSWORD: "apipassword"
      MONGODB_DATABASE: omnidb
      FLASK_ENV: production
      JWT_SECRET_KEY: "omni-street-jwt-secret-key"
      MODEL_PATH: "Models/"
      API_KEY: "c0opefv48v6rduk5oegg"
      FORGOT_API_KEY: "EE4DxQm6DjgeSuK2c6qsBzvmhhz66vyh"
      AI_API_KEY: "y4umsVpFUcVZsGkpSqntqPet7PQp5HZE"
    volumes:
      - appdata:/var/www/
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
