version: "3.7"
services:
  client:
    image: omni-web
    build:
      context: ./frontend
      dockerfile: Prod.Dockerfile
    ports:
      - "4000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend

  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: omnidb
      MONGODB_DATA_DIR: /data/db
    volumes:
      - ./db:/home/db
      - mongodbdata:/data/db
    networks:
      - backend

  api:
    image: omni-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --workers 10 --timeout 300 --bind 0.0.0.0:5000 app:app
    environment:
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "apiuser"
      MONGODB_PASSWORD: "apipassword"
      MONGODB_DATABASE: omnidb
      FLASK_ENV: production
      JWT_SECRET_KEY: "omni-street-jwt-secret-key"
      MODEL_PATH: "Models/"
      AI_API_KEY: "c0opefv48v6rduk5oegg"
      API_KEY: "EE4DxQm6DjgeSuK2c6qsBzvmhhz66vyh"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      RESET_TOKEN: "8612781060606271"
    volumes:
      - appdata:/var/www/
    depends_on:
      - mongodb
      - redis
    networks:
      - frontend
      - backend

  worker:
    image: omni-worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --app=tasks.celery worker --loglevel=info
    environment: 
      FLASK_ENV: production
      MODEL_PATH: "Models/"
      AI_API_KEY: "c0opefv48v6rduk5oegg"
      API_KEY: "EE4DxQm6DjgeSuK2c6qsBzvmhhz66vyh"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - appdata:/var/www/
    depends_on:
      - api
      - redis
    networks: 
      - backend
  
  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"
    hostname: redis
    networks: 
      - backend
  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local