version: "3.7"
services:
  client:
    image: omni-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend

  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: omnidb
      MONGODB_DATA_DIR: /data/db
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  api:
    image: omni-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --reload --workers 10 --timeout 300 --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    environment:
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: "apiuser"
      MONGODB_PASSWORD: "apipassword"
      MONGODB_DATABASE: omnidb
      FLASK_ENV: development
      JWT_SECRET_KEY: "omni-street-jwt-secret-key"
      MODEL_PATH: "Models/"
      AI_API_KEY: "c0opefv48v6rduk5oegg"
      API_KEY: "mB9dUbVRc7Qq7rvvGX5bbBsuTuq2f9Y6"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      RESET_TOKEN: "3030207007026787"
    volumes:
      - ./backend:/app
      - appdata:/var/www/
    depends_on:
      - mongodb
      - redis
    networks:
      - frontend
      - backend
  
  worker:
    image: omni-worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --app=tasks.celery worker -E --loglevel=debug
    user: nobody
    environment: 
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MODEL_PATH: "Models/"
      AI_API_KEY: "c0opefv48v6rduk5oegg"
      API_KEY: "mB9dUbVRc7Qq7rvvGX5bbBsuTuq2f9Y6"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - appdata:/var/www/
    depends_on:
      - api
      - redis
    networks: 
      - backend
  
  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"
    hostname: redis
    networks: 
      - backend

  dashboard:
    image: omni-flower
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:  flower --app=tasks.celery --port=5555 --broker=redis://redis:6379/0
    ports: 
      - "5555:5555"
    environment: 
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MODEL_PATH: "Models/"
      AI_API_KEY: "c0opefv48v6rduk5oegg"
      API_KEY: "mB9dUbVRc7Qq7rvvGX5bbBsuTuq2f9Y6"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - api
      - redis
      - worker
    networks: 
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
