$env:MONGODB_HOSTNAME = "localhost"
$env:MONGODB_DATABASE = "omnidb"
$env:FLASK_ENV = "development"
$env:JWT_SECRET_KEY = "omni-street-jwt-secret-key"
$env:MODEL_PATH = "Models/"
$env:AI_API_KEY = "c0opefv48v6rduk5oegg"
$env:API_KEY = "mB9dUbVRc7Qq7rvvGX5bbBsuTuq2f9Y6"
$env:CELERY_BROKER_URL = "redis://localhost:6379/0"
$env:CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
$env:RESET_TOKEN = "3030207007026787"
$env:FLASK_DEBUG = 1

Invoke-Expression "celery --app=tasks.celery worker -E --loglevel=debug" 
# SIG # Begin signature block
# MIIFdgYJKoZIhvcNAQcCoIIFZzCCBWMCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUPHxLTH2V2tnk1j7Qh418xHlR
# fEqgggMOMIIDCjCCAfKgAwIBAgIQegrd3EhqlI9AODQyG4TfiDANBgkqhkiG9w0B
# AQUFADAdMRswGQYDVQQDDBJMb2NhbCBDb2RlIFNpZ25pbmcwHhcNMjEwNDMwMTE0
# MzUzWhcNMjIwNDMwMTIwMzUzWjAdMRswGQYDVQQDDBJMb2NhbCBDb2RlIFNpZ25p
# bmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDsCBaYejWmce/yypLJ
# WYy/7I8IXBxkM1cABBD0t6pfdghvJAj0tzadyiRSjOKb2W4T6gOGRs3Pax+uQQKU
# rwFa6/PPvHlLPde/r/Z+8vfDmvM4NQ6jKuaSyVHiwIMjxULkOFBnEKdjuldx24rY
# 8U6uwkyv8jkUkQwQMYUBvE+kVgdtS/QJPQW6LFsjZ6IEeFj4DIIPOcw2nzyZ7MSs
# YvzQiqXyYfXfRHSlaWYx0c/Yi63EajFeymWKqrH4UdrjyDCPWfRT4ZKz6ZauGkbB
# odEbjsAzv5+wOQFXgFTSl2/eJ9+SDQAnJYWXdzV9dFwo3SM+j6vI4Rltp7vZHLd+
# InlRAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcD
# AzAdBgNVHQ4EFgQU2IvlcFTFmfnX4c/XaEJhDI6HW0YwDQYJKoZIhvcNAQEFBQAD
# ggEBAOlHJ3O6f/nemU1IQr7v6GSWmk4UTT0CWcN+e+0UBzDxajywMyZzHItk9eO+
# HXv4K4FwJAESFxpnuy8sFLo9t0WSVT6JfZRxXCRFqXh9iSQlovctkCAsUr/1YQ+I
# EW4J7bLm4LcckHwcXenm8tCVPyi6Dc8c5g8FRueURP7bIrggNdJ7gVaKFkg5XxsH
# wLSYrLzWyu9A+Pmr0tpXJIe2uu414poi+foAIniP25GeKDxcezRRNCws9fvqqzSf
# i2s74WRW33swU3Q2hv0/Cq80KE+qLT7V70nU6fQ64SEnto6qeFKcFJ98eZiYMuUy
# f0KRjUN8lIn/0C5NxkcOH7qfuZIxggHSMIIBzgIBATAxMB0xGzAZBgNVBAMMEkxv
# Y2FsIENvZGUgU2lnbmluZwIQegrd3EhqlI9AODQyG4TfiDAJBgUrDgMCGgUAoHgw
# GAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGC
# NwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQx
# FgQU1EwqwRaWapTf9XdL9MW1/CpVpmQwDQYJKoZIhvcNAQEBBQAEggEAL+wnLLvj
# Y8kRXsF/vlHFrrZX5MhhPVeKI4bS24bpJJX40YJHp2iSTWoCQwBipL1VXGJ7zbp2
# zys+Sf76Q23KlOrkZ2bpls+xmnkqBM5OMM1Bon1d2QgFWo6CPMijOtoe2RwZZZs1
# ejN14uZX7TNVBQQuSSQlHSfsCmuAEXjNURjdtABoSLDG2J454Dnw8KfLvb5fwdnp
# AAbSQNiZpG0G4OX38X+2eGsaHiFYj3KSpj94eu224f0DhxF2QxvmAOXWMp0h+NfY
# fsCstU+Z27hEYcTHJJYkbuJqCez1YYttZOFuzO3g3yp6xpSHuNFmwbIC5oYIMWh5
# IR6f5Mmd2t1IAQ==
# SIG # End signature block
